info:
  version: '@project.version@'
  stage: dev

server:
  port: '@server.port@'

management:
  security:
    flag: false
  metrics:
    export:
      statsd:
        enabled: false
        flavor: etsy
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: @project.name@
  output:
    ansi:
      enabled: always
  jpa:
    database: postgresql
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        default_schema: three_ds_server_storage
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/three_ds_server_storage
    username: postgres
    password: postgres
  flyway:
    schemas: three_ds_server_storage
    url: jdbc:postgresql://localhost:5432/three_ds_server_storage
    user: postgres
    password: postgres

client:
  three-ds-server:
    url: http://localhost:8080/sdk
    readTimeout: 1860000
    connectTimeout: 5000
