server:
  port: '@server.port@'

management:
  security:
    flag: false
  metrics:
    export:
      statsd:
        enabled: false
        flavor: etsy
  endpoint.health.show-details: always

spring:
  application:
    name: @project.name@
  output:
    ansi:
      enabled: always
  jpa:
    database: postgresql
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        default_schema: three_ds_server_storage
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/three_ds_server_storage
    username: changeit
    password: changeit
  flyway:
    schemas: three_ds_server_storage
    url: jdbc:postgresql://localhost:5432/three_ds_server_storage
    user: changeit
    password: changeit

info:
  version: '@project.version@'
  stage: dev
